using System;
using System.Collections.Generic;
using Microsoft.SqlServer.TransactSql.ScriptDom;

namespace SQLsense.Core.Analysis
{
    public enum SqlContextState
    {
        Unknown,
        SelectColumns,
        FromTables,
        JoinTables,
        JoinOnCondition,
        WhereCondition,
        UpdateTable,
        UpdateSetColumns,
        InsertTable,
        GroupByColumns,
        OrderByColumns,
        ExecProcedure,
        AlterProcedure,
        AlterView,
        AlterFunction
    }

    /// <summary>
    /// Analyzes the raw token stream generated by ScriptDom to accurately predict the user's intent 
    /// (e.g., "Selecting Columns", "Updating Table", "Setting Update Columns") even when the 
    /// overall AST is unparseable due to incomplete syntax.
    /// </summary>
    public class ContextStateAnalyzer
    {
        public static SqlContextState DetermineState(string fullText, int caretPosition)
        {
            if (string.IsNullOrWhiteSpace(fullText))
                return SqlContextState.Unknown;

            try
            {
                var parser = new TSql160Parser(true);
                using (var reader = new System.IO.StringReader(fullText))
                {
                    IList<ParseError> errors;
                    var fragment = parser.Parse(reader, out errors);
                    
                    if (fragment != null && fragment.ScriptTokenStream != null)
                    {
                        var tokens = fragment.ScriptTokenStream;
                        int currentIndex = GetTokenIndexAtCaret(tokens, caretPosition);

                        if (currentIndex < 0) return SqlContextState.Unknown;

                        // Start walking backwards from the caret to find the defining structural keyword
                        for (int i = currentIndex; i >= 0; i--)
                        {
                            var token = tokens[i];
                            
                            // Skip whitespace, comments and EOF
                            if (token.TokenType == TSqlTokenType.WhiteSpace || 
                                token.TokenType == TSqlTokenType.SingleLineComment || 
                                token.TokenType == TSqlTokenType.MultilineComment ||
                                token.TokenType == TSqlTokenType.EndOfFile)
                            {
                                continue;
                            }

                            if (string.IsNullOrEmpty(token.Text)) continue;

                            string text = token.Text.ToUpperInvariant();

                            // 1. Structural Boundaries (Statements)
                            if (text == "SELECT") return SqlContextState.SelectColumns;
                            if (text == "FROM")
                            {
                                // If the caret is physically placed BEFORE the 'FROM' 
                                // (e.g., SELECT t0.[caret] FROM), then we are still in SELECT.
                                if (caretPosition <= token.Offset)
                                {
                                    continue;
                                }
                                // Check if a table/alias has already been typed after FROM.
                                // e.g., FROM dbo.Categories [caret] -> table finished, expect keyword
                                if (HasTableOrAliasAfterFrom(tokens, i, currentIndex))
                                {
                                    return SqlContextState.Unknown; // Keyword-only zone
                                }
                                return SqlContextState.FromTables;
                            }
                            if (text == "JOIN")
                            {
                                if (caretPosition <= token.Offset) continue;
                                return SqlContextState.JoinTables;
                            }
                            if (text == "ON")
                            {
                                if (caretPosition <= token.Offset) continue;
                                return SqlContextState.JoinOnCondition;
                            }
                            if (text == "WHERE")
                            {
                                if (caretPosition <= token.Offset) continue;
                                
                                // Check if the very next meaningful token (or current) is an assignment/comparison
                                if (IsAssigningValue(tokens, i, currentIndex))
                                {
                                    return SqlContextState.Unknown; // Suppress tables/columns if typing value
                                }
                                return SqlContextState.WhereCondition;
                            }
                            
                            if (text == "UPDATE")
                            {
                                // Did they already type the table name and are now pressing space?
                                if (HasTableNameAfterUpdate(tokens, i, currentIndex))
                                {
                                    return SqlContextState.UpdateSetColumns; // They need SET
                                }
                                return SqlContextState.UpdateTable;
                            }
                            if (text == "SET")
                            {
                                if (IsAssigningValue(tokens, i, currentIndex)) return SqlContextState.Unknown;
                                if (IsAssignmentFinished(tokens, i, currentIndex)) return SqlContextState.Unknown; // They are typing WHERE or another keyword
                                return SqlContextState.UpdateSetColumns;
                            }
                            
                            if (text == "INSERT") return SqlContextState.InsertTable;
                            if (text == "GROUP") return SqlContextState.GroupByColumns;
                            if (text == "ORDER") return SqlContextState.OrderByColumns;
                            if (text == "EXEC" || text == "EXECUTE") return SqlContextState.ExecProcedure;

                            if (text == "ALTER")
                            {
                                // Look forward from ALTER to find the object type keyword
                                for (int j = i + 1; j < tokens.Count; j++)
                                {
                                    var nextToken = tokens[j];
                                    if (nextToken.TokenType == TSqlTokenType.WhiteSpace) continue;
                                    string nextText = nextToken.Text.ToUpperInvariant();
                                    if (nextText == "PROC" || nextText == "PROCEDURE") return SqlContextState.AlterProcedure;
                                    if (nextText == "VIEW") return SqlContextState.AlterView;
                                    if (nextText == "FUNCTION") return SqlContextState.AlterFunction;
                                    break; // Unknown ALTER target
                                }
                            }

                            // Non-structural tokens (identifiers, dots, operators, literals, parens, etc.)
                            // Skip these and continue searching backwards for the nearest structural keyword.
                            continue;
                        }
                    }
                }
            }
            catch
            {
                // Fallback to Unknown if parsing critically fails
            }

            return SqlContextState.Unknown;
        }

        private static int GetTokenIndexAtCaret(IList<TSqlParserToken> tokens, int caretPosition)
        {
            for (int i = tokens.Count - 1; i >= 0; i--)
            {
                if (tokens[i].Offset <= caretPosition)
                {
                    return i;
                }
            }
            return -1;
        }

        private static bool HasTableNameAfterUpdate(IList<TSqlParserToken> tokens, int updateIndex, int currentIndex)
        {
            // If the user hasn't typed a space after the table name, they are still typing the table name.
            // e.g., UPDATE [caret], UPDATE dbo.[caret], UPDATE dbo.Advert[caret]
            
            // We need to look if there's any non-whitespace meaningful token, and THEN a whitespace / structural break 
            // before the caret position to prove the table name string is "closed".
            
            bool foundIdentifier = false;
            for (int i = updateIndex + 1; i <= currentIndex; i++)
            {
                var type = tokens[i].TokenType;
                
                if (type == TSqlTokenType.WhiteSpace || 
                    type == TSqlTokenType.SingleLineComment || 
                    type == TSqlTokenType.MultilineComment ||
                    type == TSqlTokenType.EndOfFile)
                {
                    if (foundIdentifier && type == TSqlTokenType.WhiteSpace)
                    {
                        return true;
                    }
                    continue;
                }

                if (type == TSqlTokenType.Identifier || type == TSqlTokenType.Dot || type == TSqlTokenType.QuotedIdentifier)
                {
                    foundIdentifier = true;
                }
            }
            
            // If they are actively typing the identifier at EOF (like "UPDATE A"),
            // we return false because the table name isn't officially "closed" with a space yet.
            // They need Table suggestions!
            return false;
        }

        /// <summary>
        /// Checks if a table/view name (optionally followed by an alias) has been completed after FROM.
        /// Returns true if the user has finished typing the table source and is now in keyword-only territory.
        /// e.g., "FROM dbo.Categories " -> true  (table name closed with space)
        /// e.g., "FROM dbo.Categories t0 " -> true  (table+alias closed)
        /// e.g., "FROM " -> false  (still typing)
        /// e.g., "FROM dbo." -> false  (schema prefix not complete)
        /// e.g., "FROM dbo.Categories," -> false  (comma = another table expected)
        /// </summary>
        private static bool HasTableOrAliasAfterFrom(IList<TSqlParserToken> tokens, int fromIndex, int currentIndex)
        {
            bool foundIdentifier = false;
            bool foundWhitespaceAfterIdentifier = false;
            
            for (int i = fromIndex + 1; i <= currentIndex; i++)
            {
                var type = tokens[i].TokenType;
                
                if (type == TSqlTokenType.EndOfFile)
                {
                    continue; // EOF doesn't count as whitespace after identifier
                }

                if (type == TSqlTokenType.WhiteSpace || 
                    type == TSqlTokenType.SingleLineComment || 
                    type == TSqlTokenType.MultilineComment)
                {
                    if (foundIdentifier)
                    {
                        foundWhitespaceAfterIdentifier = true;
                    }
                    continue;
                }

                // Dot is part of schema qualification (dbo.Categories) - continue building the identifier
                if (type == TSqlTokenType.Dot)
                {
                    // Only reset whitespace flag if we haven't completed the table name yet
                    if (!foundWhitespaceAfterIdentifier)
                    {
                        continue; // dbo. still part of table reference
                    }
                    // If we had whitespace after identifier but now see a dot, this is alias.column => not FROM zone anymore
                    return false;
                }

                // Comma means user wants another table => not done
                if (type == TSqlTokenType.Comma)
                {
                    return false;
                }

                // Left paren could be subquery "FROM (" or function
                if (type == TSqlTokenType.LeftParenthesis)
                {
                    return false;
                }

                if (type == TSqlTokenType.Identifier || type == TSqlTokenType.QuotedIdentifier)
                {
                    if (foundWhitespaceAfterIdentifier)
                    {
                        // This is either an alias OR a keyword being typed.
                        // We've found: FROM table [space] something
                        // Check if this "something" is still being actively typed at the caret
                        var tok = tokens[i];
                        if (tok.Offset + tok.Text.Length >= tokens[currentIndex].Offset)
                        {
                            // The token is touching the caret - user may be typing alias or keyword.
                            // We can't tell the difference, so return false to SHOW suggestions (keywords + potential)
                            return false;
                        }
                        else
                        {
                            // Token is completed and there's more after it.
                            // This was the alias. Mark that we've now consumed table+alias.
                            // Look ahead to see if there's another whitespace after this alias.
                            foundIdentifier = true;
                            foundWhitespaceAfterIdentifier = false;
                            continue;
                        }
                    }
                    else
                    {
                        foundIdentifier = true;
                    }
                }
            }
            
            // If we found an identifier with whitespace after it, and nothing more meaningful:
            // It means the user finished typing the table (and optionally alias) and there's a trailing space.
            if (foundIdentifier && foundWhitespaceAfterIdentifier)
            {
                return true;
            }
            
            return false;
        }

        private static bool IsAssigningValue(IList<TSqlParserToken> tokens, int startIndex, int currentIndex)
        {
            // Scan from the keyword (e.g., WHERE) up to the caret. 
            // If the last meaningful symbol typed was = < >, we are waiting for a value.
            for (int i = currentIndex; i > startIndex; i--)
            {
                 if (tokens[i].TokenType == TSqlTokenType.WhiteSpace || 
                     tokens[i].TokenType == TSqlTokenType.EndOfFile || 
                     string.IsNullOrEmpty(tokens[i].Text)) continue;
                 
                 // If we hit a comma, it means they are trying to assign another column.
                 if (tokens[i].TokenType == TSqlTokenType.Comma)
                 {
                     return false;
                 }

                 string text = tokens[i].Text;
                 if (text == "=" || text == ">" || text == "<" || text == ">=" || text == "<=" || text == "<>")
                 {
                     return true;
                 }
                 
                 // If we hit an identifier before hitting an equal sign, we are typing the column name
                 if (tokens[i].TokenType == TSqlTokenType.Identifier)
                 {
                     return false; 
                 }
            }
            return false;
        }

        private static bool IsAssignmentFinished(IList<TSqlParserToken> tokens, int startIndex, int currentIndex)
        {
            // Scan from the caret backwards. We are looking for: 
            // [Identifier/Keyword we are currently typing (e.g. "w")] -> [Space] -> [Value (String/Number/Binary)] -> [=]
            
            bool foundCurrentIdentifier = false;

            for (int i = currentIndex; i > startIndex; i--)
            {
                var type = tokens[i].TokenType;
                
                if (type == TSqlTokenType.WhiteSpace || type == TSqlTokenType.EndOfFile || string.IsNullOrEmpty(tokens[i].Text)) 
                    continue;

                // Step 1: Detect the word they are actively typing (like "w")
                if (!foundCurrentIdentifier)
                {
                    if (type == TSqlTokenType.Identifier || type == TSqlTokenType.QuotedIdentifier)
                    {
                        foundCurrentIdentifier = true;
                        continue;
                    }
                    else
                    {
                        // The very first meaningful thing before the caret IS NOT an identifier (e.g. it's a comma `,` or a number `1`)
                        // That means they are still actively writing the value, or preparing for the next assignment.
                        // In either case, they have not yet started typing the NEXT structural keyword.
                        return false;
                    }
                }

                // Step 2: Now that we found the identifier, see if a Value and '=' exists before it, WITHOUT hitting a comma.
                if (type == TSqlTokenType.Comma)
                {
                    // A comma means they are about to assign ANOTHER column.
                    return false;
                }
                
                // Allow skipping over the assigned value (e.g. `1`, `'test'`, `@param`)
                if (type == TSqlTokenType.Integer || type == TSqlTokenType.Numeric || type == TSqlTokenType.AsciiStringLiteral || 
                    type == TSqlTokenType.UnicodeStringLiteral || type == TSqlTokenType.HexLiteral || 
                    type == TSqlTokenType.Variable || type == TSqlTokenType.Null || type == TSqlTokenType.Real)
                {
                    continue;
                }
                
                // Also allow skipping over built-in function calls (like GETDATE())
                if (type == TSqlTokenType.RightParenthesis || type == TSqlTokenType.LeftParenthesis || type == TSqlTokenType.Identifier)
                {
                    continue;
                }
                
                // If we see an assignment operator, it means the identifier we are typing is occurring AFTER an assignment.
                // e.g. Col = 1 w
                string text = tokens[i].Text;
                if (text == "=" || text == ">" || text == "<" || text == ">=" || text == "<=" || text == "<>")
                {
                    return true;
                }
                
                // If we hit anything else (like another keyword before finding '='), then we aren't safely post-assignment
                break;
            }
            
            return false;
        }

    }
}
