using System;
using System.Collections.Generic;
using Microsoft.SqlServer.TransactSql.ScriptDom;

namespace SQLsense.Core.Analysis
{
    public enum SqlContextState
    {
        Unknown,
        SelectColumns,
        FromTables,
        JoinTables,
        JoinOnCondition,
        WhereCondition,
        UpdateTable,
        UpdateSetColumns,
        InsertTable,
        GroupByColumns,
        OrderByColumns
    }

    /// <summary>
    /// Analyzes the raw token stream generated by ScriptDom to accurately predict the user's intent 
    /// (e.g., "Selecting Columns", "Updating Table", "Setting Update Columns") even when the 
    /// overall AST is unparseable due to incomplete syntax.
    /// </summary>
    public class ContextStateAnalyzer
    {
        public static SqlContextState DetermineState(string fullText, int caretPosition)
        {
            if (string.IsNullOrWhiteSpace(fullText))
                return SqlContextState.Unknown;

            try
            {
                var parser = new TSql160Parser(true);
                using (var reader = new System.IO.StringReader(fullText))
                {
                    IList<ParseError> errors;
                    var fragment = parser.Parse(reader, out errors);
                    
                    if (fragment != null && fragment.ScriptTokenStream != null)
                    {
                        var tokens = fragment.ScriptTokenStream;
                        int currentIndex = GetTokenIndexAtCaret(tokens, caretPosition);

                        if (currentIndex < 0) return SqlContextState.Unknown;

                        // Start walking backwards from the caret to find the defining structural keyword
                        for (int i = currentIndex; i >= 0; i--)
                        {
                            var token = tokens[i];
                            
                            // Skip whitespace, comments and EOF
                            if (token.TokenType == TSqlTokenType.WhiteSpace || 
                                token.TokenType == TSqlTokenType.SingleLineComment || 
                                token.TokenType == TSqlTokenType.MultilineComment ||
                                token.TokenType == TSqlTokenType.EndOfFile)
                            {
                                continue;
                            }

                            if (string.IsNullOrEmpty(token.Text)) continue;

                            string text = token.Text.ToUpperInvariant();

                            // 1. Structural Boundaries (Statements)
                            if (text == "SELECT") return SqlContextState.SelectColumns;
                            if (text == "FROM")
                            {
                                // If the caret is physically placed BEFORE the 'FROM' 
                                // (e.g., SELECT t0.[caret] FROM), then we are still in SELECT.
                                if (caretPosition <= token.Offset)
                                {
                                    continue;
                                }
                                return SqlContextState.FromTables;
                            }
                            if (text == "JOIN")
                            {
                                if (caretPosition <= token.Offset) continue;
                                return SqlContextState.JoinTables;
                            }
                            if (text == "ON")
                            {
                                if (caretPosition <= token.Offset) continue;
                                return SqlContextState.JoinOnCondition;
                            }
                            if (text == "WHERE")
                            {
                                if (caretPosition <= token.Offset) continue;
                                
                                // Check if the very next meaningful token (or current) is an assignment/comparison
                                if (IsAssigningValue(tokens, i, currentIndex))
                                {
                                    return SqlContextState.Unknown; // Suppress tables/columns if typing value
                                }
                                return SqlContextState.WhereCondition;
                            }
                            
                            if (text == "UPDATE")
                            {
                                // Did they already type the table name and are now pressing space?
                                if (HasTableNameAfterUpdate(tokens, i, currentIndex))
                                {
                                    return SqlContextState.UpdateSetColumns; // They need SET
                                }
                                return SqlContextState.UpdateTable;
                            }
                            if (text == "SET")
                            {
                                if (IsAssigningValue(tokens, i, currentIndex)) return SqlContextState.Unknown;
                                if (IsAssignmentFinished(tokens, i, currentIndex)) return SqlContextState.Unknown; // They are typing WHERE or another keyword
                                return SqlContextState.UpdateSetColumns;
                            }
                            
                            if (text == "INSERT") return SqlContextState.InsertTable;
                            if (text == "GROUP") return SqlContextState.GroupByColumns; // Simplification
                            if (text == "ORDER") return SqlContextState.OrderByColumns;
                        }
                    }
                }
            }
            catch
            {
                // Fallback to Unknown if parsing critically fails
            }

            return SqlContextState.Unknown;
        }

        private static int GetTokenIndexAtCaret(IList<TSqlParserToken> tokens, int caretPosition)
        {
            for (int i = tokens.Count - 1; i >= 0; i--)
            {
                if (tokens[i].Offset <= caretPosition)
                {
                    return i;
                }
            }
            return -1;
        }

        private static bool HasTableNameAfterUpdate(IList<TSqlParserToken> tokens, int updateIndex, int currentIndex)
        {
            // If the user hasn't typed a space after the table name, they are still typing the table name.
            // e.g., UPDATE [caret], UPDATE dbo.[caret], UPDATE dbo.Advert[caret]
            
            // We need to look if there's any non-whitespace meaningful token, and THEN a whitespace / structural break 
            // before the caret position to prove the table name string is "closed".
            
            bool foundIdentifier = false;
            for (int i = updateIndex + 1; i <= currentIndex; i++)
            {
                var type = tokens[i].TokenType;
                
                if (type == TSqlTokenType.WhiteSpace || 
                    type == TSqlTokenType.SingleLineComment || 
                    type == TSqlTokenType.MultilineComment ||
                    type == TSqlTokenType.EndOfFile)
                {
                    if (foundIdentifier && type == TSqlTokenType.WhiteSpace)
                    {
                        return true;
                    }
                    continue;
                }

                if (type == TSqlTokenType.Identifier || type == TSqlTokenType.Dot || type == TSqlTokenType.QuotedIdentifier)
                {
                    foundIdentifier = true;
                }
            }
            
            // If they are actively typing the identifier at EOF (like "UPDATE A"),
            // we return false because the table name isn't officially "closed" with a space yet.
            // They need Table suggestions!
            return false;
        }

        private static bool IsAssigningValue(IList<TSqlParserToken> tokens, int startIndex, int currentIndex)
        {
            // Scan from the keyword (e.g., WHERE) up to the caret. 
            // If the last meaningful symbol typed was = < >, we are waiting for a value.
            for (int i = currentIndex; i > startIndex; i--)
            {
                 if (tokens[i].TokenType == TSqlTokenType.WhiteSpace || 
                     tokens[i].TokenType == TSqlTokenType.EndOfFile || 
                     string.IsNullOrEmpty(tokens[i].Text)) continue;
                 
                 // If we hit a comma, it means they are trying to assign another column.
                 if (tokens[i].TokenType == TSqlTokenType.Comma)
                 {
                     return false;
                 }

                 string text = tokens[i].Text;
                 if (text == "=" || text == ">" || text == "<" || text == ">=" || text == "<=" || text == "<>")
                 {
                     return true;
                 }
                 
                 // If we hit an identifier before hitting an equal sign, we are typing the column name
                 if (tokens[i].TokenType == TSqlTokenType.Identifier)
                 {
                     return false; 
                 }
            }
            return false;
        }

        private static bool IsAssignmentFinished(IList<TSqlParserToken> tokens, int startIndex, int currentIndex)
        {
            // Scan from the caret backwards. We are looking for: 
            // [Identifier/Keyword we are currently typing (e.g. "w")] -> [Space] -> [Value (String/Number/Binary)] -> [=]
            
            bool foundCurrentIdentifier = false;

            for (int i = currentIndex; i > startIndex; i--)
            {
                var type = tokens[i].TokenType;
                
                if (type == TSqlTokenType.WhiteSpace || type == TSqlTokenType.EndOfFile || string.IsNullOrEmpty(tokens[i].Text)) 
                    continue;

                // Step 1: Detect the word they are actively typing (like "w")
                if (!foundCurrentIdentifier)
                {
                    if (type == TSqlTokenType.Identifier || type == TSqlTokenType.QuotedIdentifier)
                    {
                        foundCurrentIdentifier = true;
                        continue;
                    }
                    else
                    {
                        // The very first meaningful thing before the caret IS NOT an identifier (e.g. it's a comma `,` or a number `1`)
                        // That means they are still actively writing the value, or preparing for the next assignment.
                        // In either case, they have not yet started typing the NEXT structural keyword.
                        return false;
                    }
                }

                // Step 2: Now that we found the identifier, see if a Value and '=' exists before it, WITHOUT hitting a comma.
                if (type == TSqlTokenType.Comma)
                {
                    // A comma means they are about to assign ANOTHER column.
                    return false;
                }
                
                // Allow skipping over the assigned value (e.g. `1`, `'test'`, `@param`)
                if (type == TSqlTokenType.Integer || type == TSqlTokenType.Numeric || type == TSqlTokenType.AsciiStringLiteral || 
                    type == TSqlTokenType.UnicodeStringLiteral || type == TSqlTokenType.HexLiteral || 
                    type == TSqlTokenType.Variable || type == TSqlTokenType.Null || type == TSqlTokenType.Real)
                {
                    continue;
                }
                
                // Also allow skipping over built-in function calls (like GETDATE())
                if (type == TSqlTokenType.RightParenthesis || type == TSqlTokenType.LeftParenthesis || type == TSqlTokenType.Identifier)
                {
                    continue;
                }
                
                // If we see an assignment operator, it means the identifier we are typing is occurring AFTER an assignment.
                // e.g. Col = 1 w
                string text = tokens[i].Text;
                if (text == "=" || text == ">" || text == "<" || text == ">=" || text == "<=" || text == "<>")
                {
                    return true;
                }
                
                // If we hit anything else (like another keyword before finding '='), then we aren't safely post-assignment
                break;
            }
            
            return false;
        }
    }
}
